unbind = SUPER, T
unbind = SUPER, E
unbind = SUPER, W
unbind = Super+Alt, Space

bind = Super, W, killactive
bind = Super, T, togglefloating

bind = Super+Shift, T, exec, ~/.config/hypr/hyprland/scripts/launch_first_available.sh  "${TERMINAL}" "kitty -1" "foot" "alacritty" "wezterm" "konsole" "kgx" "uxterm" "xterm" # [hidden] (terminal) (alt) 
bind = Super+Shift, F, exec, ~/.config/hypr/hyprland/scripts/launch_first_available.sh "dolphin" "nautilus" "nemo" "thunar" "${TERMINAL}" "kitty -1 fish -c yazi" # File manager 
bind = Super+Shift, B, exec, ~/.config/hypr/hyprland/scripts/launch_first_available.sh "google-chrome-stable" "zen-browser" "firefox" "floorp" "brave" "chromium" "microsoft-edge-stable" "opera" "librewolf"
bind = Super+Shift, Z, exec, ~/.config/hypr/hyprland/scripts/launch_first_available.sh "code" "codium" "cursor" "zed" "zedit" "zeditor" "kate" "gnome-text-editor" "emacs" "command -v nvim && kitty -1 nvim" "command -v micro && kitty -1 micro" # Code editor 