#!/bin/bash

CONF_DIR="$HOME/.config/hypr/cocoa"
mkdir -p "$CONF_DIR"

echo "--- Hyprland Keyboard Configuration ---"

echo "Enter XKB layout name(s). Use commas for multiple layouts."
echo "Examples: 'us', 'jp', 'us,jp', 'gb,de'"
read -p "Layout(s): " LAYOUT

if [ -z "$LAYOUT" ]; then
    echo "Error: Layout is required."
    exit 1
fi

echo -e "\nEnter XKB options (leave empty for none)."
echo "Examples: 'ctrl:nocaps', 'grp:alt_shift_toggle', 'grp:win_space_toggle'"
read -p "Options: " KB_OPTIONS

echo -e "\nTouchpad Settings:"
if [ -d /sys/class/power_supply/BAT0 ]; then
    echo "(Note: Battery detected, likely a laptop)"
fi

NATURAL_SCROLL="false"
read -p "Enable natural scroll? (y/n, default: n): " USE_NATURAL
[[ "$USE_NATURAL" =~ ^[Yy]$ ]] && NATURAL_SCROLL="true"

cat <<EOF > "$CONF_DIR/keyboard.conf"
# Generated by dotstrap
input {
    kb_layout = $LAYOUT
    kb_model = pc105
    kb_options = $KB_OPTIONS

    follow_mouse = 1

    touchpad {
        natural_scroll = $NATURAL_SCROLL
    }
}
EOF

HYPR_MAIN="$HOME/.config/hypr/hyprland.conf"
MARK_BEGIN="# >>> dotfiles: keyboard.conf"
MARK_END="# <<< dotfiles: keyboard.conf"
SOURCE_LINE="source = ~/.config/hypr/cocoa/keyboard.conf"

if [ -f "$HYPR_MAIN" ]; then
    # Always remove existing block to ensure updates are applied
    if grep -q "$MARK_BEGIN" "$HYPR_MAIN"; then
        sed -i "/$MARK_BEGIN/,/$MARK_END/d" "$HYPR_MAIN"
    fi
    # Insert at the beginning of the file with markers
    sed -i "1i $MARK_BEGIN\n$SOURCE_LINE\n$MARK_END" "$HYPR_MAIN"
    echo ">> Linked $SOURCE_LINE to hyprland.conf"
else
    echo -e "$MARK_BEGIN\n$SOURCE_LINE\n$MARK_END" > "$HYPR_MAIN"
    echo ">> Created new hyprland.conf with $SOURCE_LINE"
fi

echo -e "\nConfiguration saved to $CONF_DIR/keyboard.conf"
echo "Layout: $LAYOUT"
[ -n "$KB_OPTIONS" ] && echo "Options: $KB_OPTIONS"
